/**
 * Fix Service — RAG-powered fix generation via the hosted insights API.
 *
 * Calls getInsights() with a single-violation payload and extracts the
 * per-violation guidance (fixHtml, explanation, techniques, failures).
 * Falls back to local FIX_TEMPLATES when the API is unavailable.
 *
 * Surfaces tier info (free/paid, daily remaining, rate limit state) from
 * API response headers so Claude can inform the developer about their
 * plan status rather than silently degrading.
 */

import { getInsights, InsightApiError } from '../../concepts/a11y-scanner/insight-client.ts';
import type { InsightResponse, RenderMode } from '../../concepts/a11y-scanner/insight-client.ts';
import { logError } from './log.ts';
import { FIX_TEMPLATES } from '../../testing-agent/fix-templates.ts';
import type {
  ViolationGuidance,
  GroundedElement,
  RejectedTechnique,
  Confidence,
  Rationale,
  FixTier,
  GroundingPath,
  ArtifactVersions,
  NodeChecks,
} from '../../types/a11y';
import { getRuleMetadata } from './axe-rule-metadata.ts';

export interface FixRequest {
  ruleId: string;
  html: string;
  parentHtml?: string;
  childrenHtml?: string;
  siblingHtml?: string;
  failureSummary?: string;
  /** axe per-node check buckets (any/all/none) — lets Tier-0 templates read structured data. */
  checks?: NodeChecks;
  url?: string;
  /**
   * Render mode for the insights round-trip (docs §8). Defaults to
   * 'grounded_semantic' (get_fix's mode). scan_and_fix passes 'deterministic'.
   * Both skip the Path-A LLM narrative — the fix path only consumes the
   * ontology-grounded violationGuidance.
   */
  mode?: RenderMode;
  /** Correlation id (from the calling tool) forwarded to the server as X-Scan-ID. */
  scanId?: string;
}

export interface TierInfo {
  tier: string;
  dailyRemaining?: number;
  dailyLimit?: number;
}

export interface RateLimitInfo {
  tier: string;
  dailyUsed?: number;
  dailyLimit?: number;
  resetsAt?: string;
  expired?: string;
  message: string;
}

export interface FixResponse {
  fixHtml: string;
  explanation: string;
  wcagCriteria: Array<{ sc: string; title: string; level: string }>;
  techniques: Array<{ id: string; description: string; codeSnippet?: string }>;
  failures: Array<{ id: string; description: string; codeSnippet?: string }>;
  source: 'rag' | 'template';
  tierInfo?: TierInfo;
  rateLimitInfo?: RateLimitInfo;
  // Grounding-gate verdict (present only on RAG fixes that ran the ontology gate).
  grounded?: boolean;
  rejectedTechniques?: RejectedTechnique[];
  element?: GroundedElement;
  // ---- Grounded Artifact fields (docs/grounded-artifact-schema.md) ----
  path?: GroundingPath;
  confidence?: Confidence;
  rationale?: Rationale;
  fixTier?: FixTier;
  versions?: ArtifactVersions;
  /** Render mode the tool requested (docs §5/§8): self-describes the surface. */
  renderMode?: RenderMode;
  /** LLM budget (per-request or global daily) was exhausted; only template/KB tiers ran. */
  budgetExhausted?: boolean;
  /** A generated fix was discarded by the server-side output sanitizer (reason codes). */
  fixRejected?: string;
}

export interface ExplainResponse {
  ruleId: string;
  description: string;
  impact: string;
  wcagCriteria: Array<{ sc: string; title: string; level: string }>;
  techniques: Array<{ id: string; description: string; codeSnippet?: string }>;
  failures: Array<{ id: string; description: string; codeSnippet?: string }>;
  fixGuidance: string;
  source: 'rag' | 'metadata';
  tierInfo?: TierInfo;
  rateLimitInfo?: RateLimitInfo;
}

/**
 * Get a RAG-powered fix for a single violation. Falls back to templates.
 * Surfaces rate limit and tier info from the API when available.
 */
export async function getFix(req: FixRequest): Promise<FixResponse> {
  const metadata = getRuleMetadata(req.ruleId);

  // Try RAG API first
  try {
    const insights = await callInsightsForViolation(req);
    const guidance = findGuidance(insights, req.ruleId);

    if (guidance?.fixHtml) {
      return {
        fixHtml: guidance.fixHtml,
        explanation: guidance.fixExplanation ?? 'Fix generated by RAG corpus analysis.',
        wcagCriteria: guidance.criteria.map((c) => ({ sc: c.sc_num, title: c.title, level: c.level })),
        techniques: guidance.techniques.map((t) => ({
          id: t.technique_id,
          description: t.description,
          codeSnippet: t.code_snippet,
        })),
        failures: guidance.failures.map((f) => ({
          id: f.failure_id,
          description: f.description,
          codeSnippet: f.code_snippet,
        })),
        source: 'rag',
        renderMode: req.mode ?? 'grounded_semantic',
        ...(guidance.grounded !== undefined ? { grounded: guidance.grounded } : {}),
        ...(guidance.rejectedTechniques ? { rejectedTechniques: guidance.rejectedTechniques } : {}),
        ...(guidance.element ? { element: guidance.element } : {}),
        ...(guidance.path ? { path: guidance.path } : {}),
        ...(guidance.confidence ? { confidence: guidance.confidence } : {}),
        ...(guidance.rationale ? { rationale: guidance.rationale } : {}),
        ...(guidance.fixTier ? { fixTier: guidance.fixTier } : {}),
        ...(guidance.budgetExhausted ? { budgetExhausted: true } : {}),
        ...(guidance.fixRejected ? { fixRejected: guidance.fixRejected } : {}),
        ...(insights.versions ? { versions: insights.versions } : {}),
      };
    }

    // Guidance returned but no fixHtml → the grounding gate abstained (or found
    // no groundable fix). Preserve the honesty artifact (tier / rejected
    // techniques / rationale) instead of silently masking it with a bare
    // template. We still attach a template fixHtml as a review suggestion, but
    // the confidence block reflects the abstain verdict.
    if (guidance) {
      const templateFix = getTemplateFix(req, metadata);
      return {
        ...templateFix,
        ...(guidance.grounded !== undefined ? { grounded: guidance.grounded } : {}),
        ...(guidance.rejectedTechniques ? { rejectedTechniques: guidance.rejectedTechniques } : {}),
        ...(guidance.element ? { element: guidance.element } : {}),
        ...(guidance.path ? { path: guidance.path } : {}),
        ...(guidance.confidence ? { confidence: guidance.confidence } : {}),
        ...(guidance.rationale ? { rationale: guidance.rationale } : {}),
        ...(guidance.fixTier ? { fixTier: guidance.fixTier } : {}),
        ...(guidance.budgetExhausted ? { budgetExhausted: true } : {}),
        ...(guidance.fixRejected ? { fixRejected: guidance.fixRejected } : {}),
        ...(insights.versions ? { versions: insights.versions } : {}),
      };
    }
  } catch (err) {
    // Check if this is a rate limit or auth error — surface it clearly
    const rateLimitInfo = parseApiError(err);
    if (rateLimitInfo) {
      logError('getFix RAG rate-limit/auth fallback → template', err, {
        scanId: req.scanId,
        ruleId: req.ruleId,
        status: err instanceof InsightApiError ? err.status : undefined,
      });
      const templateFix = getTemplateFix(req, metadata);
      return {
        ...templateFix,
        rateLimitInfo,
      };
    }
    // Other errors (network, 500, etc.) — previously fell through silently.
    // Log the cause so a "fixes came back as templates" bug report is traceable.
    logError('getFix RAG error fallback → template', err, {
      scanId: req.scanId,
      ruleId: req.ruleId,
      status: err instanceof InsightApiError ? err.status : undefined,
    });
  }

  // Fallback: local fix templates
  return getTemplateFix(req, metadata);
}

/**
 * Explain a violation with WCAG references, techniques, and fix guidance.
 * Surfaces rate limit and tier info from the API when available.
 */
export async function explainViolation(ruleId: string, scanId?: string): Promise<ExplainResponse> {
  const metadata = getRuleMetadata(ruleId);

  // Try RAG API
  try {
    const insights = await callInsightsForExplain(ruleId, scanId);
    const guidance = findGuidance(insights, ruleId);

    if (guidance) {
      return {
        ruleId,
        description: metadata?.description ?? `Axe rule: ${ruleId}`,
        impact: metadata?.impact ?? 'unknown',
        wcagCriteria: guidance.criteria.map((c) => ({ sc: c.sc_num, title: c.title, level: c.level })),
        techniques: guidance.techniques.map((t) => ({
          id: t.technique_id,
          description: t.description,
          codeSnippet: t.code_snippet,
        })),
        failures: guidance.failures.map((f) => ({
          id: f.failure_id,
          description: f.description,
          codeSnippet: f.code_snippet,
        })),
        fixGuidance: guidance.fixExplanation ?? insights.summary,
        source: 'rag',
      };
    }
  } catch (err) {
    const rateLimitInfo = parseApiError(err);
    if (rateLimitInfo) {
      logError('explainViolation RAG rate-limit/auth fallback → metadata', err, {
        scanId,
        ruleId,
        status: err instanceof InsightApiError ? err.status : undefined,
      });
      const template = FIX_TEMPLATES[ruleId];
      return {
        ruleId,
        description: metadata?.description ?? `Axe rule: ${ruleId}`,
        impact: metadata?.impact ?? 'unknown',
        wcagCriteria: metadata?.wcag ?? [],
        techniques: [],
        failures: [],
        fixGuidance: template?.errorSummary ?? 'No additional guidance available.',
        source: 'metadata',
        rateLimitInfo,
      };
    }
    // Other errors — previously fell through to metadata silently.
    logError('explainViolation RAG error fallback → metadata', err, {
      scanId,
      ruleId,
      status: err instanceof InsightApiError ? err.status : undefined,
    });
  }

  // Fallback: static metadata
  const template = FIX_TEMPLATES[ruleId];
  return {
    ruleId,
    description: metadata?.description ?? `Axe rule: ${ruleId}`,
    impact: metadata?.impact ?? 'unknown',
    wcagCriteria: metadata?.wcag ?? [],
    techniques: [],
    failures: [],
    fixGuidance: template?.errorSummary ?? 'No additional guidance available.',
    source: 'metadata',
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Parse an InsightApiError into a RateLimitInfo object.
 * Returns undefined for non-rate-limit/non-auth errors.
 */
function parseApiError(err: unknown): RateLimitInfo | undefined {
  if (!(err instanceof InsightApiError)) return undefined;

  const h = err.responseHeaders;
  const tier = h['x-aether-tier'] ?? 'unknown';

  if (err.status === 429) {
    const dailyLimit = h['x-aether-daily-limit'] ? parseInt(h['x-aether-daily-limit'], 10) : undefined;
    const dailyRemaining = h['x-aether-daily-remaining'] ? parseInt(h['x-aether-daily-remaining'], 10) : undefined;
    const resetsAt = h['x-aether-daily-reset'] ?? undefined;

    const dailyUsed = dailyLimit !== undefined && dailyRemaining !== undefined
      ? dailyLimit - dailyRemaining
      : undefined;

    return {
      tier,
      dailyUsed,
      dailyLimit,
      resetsAt,
      message: err.detail.includes('Daily free tier')
        ? `${err.detail} Upgrade at https://allchemy.io/pricing`
        : `Rate limit exceeded. ${err.detail}`,
    };
  }

  if (err.status === 403) {
    return {
      tier,
      expired: h['x-aether-expired'] ?? undefined,
      message: err.detail,
    };
  }

  if (err.status === 401) {
    return {
      tier: 'none',
      message: 'Invalid API key. Set ALLCHEMY_API_KEY with a valid key from https://beta.allchemylabs.ai (sign in with GitHub to get or rotate one)',
    };
  }

  return undefined;
}

/**
 * Generate a template-based fix (local, no API call).
 */
function getTemplateFix(
  req: FixRequest,
  metadata: ReturnType<typeof getRuleMetadata>,
): FixResponse {
  const template = FIX_TEMPLATES[req.ruleId];
  if (template) {
    const result = template.generateFix(req.html, {
      html: req.html,
      target: undefined,
      failureSummary: req.failureSummary,
      parentHtml: req.parentHtml,
      childrenHtml: req.childrenHtml,
    });
    return {
      fixHtml: result.fixHtml,
      explanation: result.explanation,
      wcagCriteria: metadata?.wcag ?? [],
      techniques: [],
      failures: [],
      source: 'template',
      renderMode: req.mode ?? 'grounded_semantic',
    };
  }

  return {
    fixHtml: req.html,
    explanation: metadata?.description ?? `No fix available for rule "${req.ruleId}".`,
    wcagCriteria: metadata?.wcag ?? [],
    techniques: [],
    failures: [],
    source: 'template',
    renderMode: req.mode ?? 'grounded_semantic',
  };
}

async function callInsightsForViolation(req: FixRequest): Promise<InsightResponse> {
  return getInsights({
    axeResults: {
      violations: [
        {
          id: req.ruleId,
          description: getRuleMetadata(req.ruleId)?.description ?? req.ruleId,
          impact: getRuleMetadata(req.ruleId)?.impact,
          nodes: [
            {
              html: req.html,
              failureSummary: req.failureSummary,
              parentHtml: req.parentHtml,
              childrenHtml: req.childrenHtml,
              siblingHtml: req.siblingHtml,
              ...(req.checks ? { checks: req.checks } : {}),
            },
          ],
        },
      ],
    },
    url: req.url ?? 'unknown',
    // get_fix defaults to grounded_semantic; scan_and_fix overrides to
    // deterministic. Both skip the Path-A narrative (docs §8).
    mode: req.mode ?? 'grounded_semantic',
  }, { scanId: req.scanId });
}

async function callInsightsForExplain(ruleId: string, scanId?: string): Promise<InsightResponse> {
  const metadata = getRuleMetadata(ruleId);
  return getInsights({
    axeResults: {
      violations: [
        {
          id: ruleId,
          description: metadata?.description ?? ruleId,
          impact: metadata?.impact,
          nodes: [{ html: `<div data-rule="${ruleId}"></div>` }],
        },
      ],
    },
    url: 'explain-only',
    // Explanation only needs ontology criteria/techniques — skip Path A.
    mode: 'deterministic',
  }, { scanId });
}

function findGuidance(
  insights: InsightResponse,
  ruleId: string,
): ViolationGuidance | undefined {
  return insights.violationGuidance?.find((g) => g.violationId === ruleId);
}
